# Generated by Django 4.2.3 on 2023-12-13 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='reported_by_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Journey', to=settings.AUTH_USER_MODEL),
        ),
    ]
