# Generated by Django 4.2.3 on 2024-01-21 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0003_alter_journey_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='companions',
            field=models.ManyToManyField(blank=True, related_name='companionJourney', to=settings.AUTH_USER_MODEL),
        ),
    ]
