# Generated by Django 4.2.3 on 2024-01-28 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0004_journey_companions'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='followed_by_users',
            field=models.ManyToManyField(blank=True, related_name='followed_journey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journey',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journey',
            name='reported_by_users',
            field=models.ManyToManyField(blank=True, related_name='reported_journey', to=settings.AUTH_USER_MODEL),
        ),
    ]
