# Generated by Django 4.2.3 on 2024-01-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_journey_followed_by_users_journey_followers_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='followers_count',
            new_name='follower_count',
        ),
    ]
