# Generated by Django 4.2.3 on 2024-02-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_rename_followers_count_journey_follower_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='groupchat',
            field=models.BooleanField(default=False),
        ),
    ]
