# Generated by Django 4.2.3 on 2024-02-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0007_journey_groupchat'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='fromJourney',
            field=models.ManyToManyField(to='journey.journey'),
        ),
    ]
