# Generated by Django 4.2.3 on 2024-02-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_fromjourney'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='fromJourney',
            new_name='journey',
        ),
    ]
