# Generated by Django 4.2.3 on 2024-02-05 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0007_journey_groupchat'),
        ('chat', '0003_rename_fromjourney_conversation_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='journey',
        ),
        migrations.AddField(
            model_name='conversation',
            name='journey',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='journey.journey'),
        ),
    ]
