# Generated by Django 4.2.3 on 2024-02-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversationmessage_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
