# Generated by Django 4.2.3 on 2023-10-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('Start', 'Start'), ('Update', 'Update'), ('Milestone', 'Milestone'), ('End', 'End')], default='START', max_length=10),
        ),
    ]
