# Generated by Django 4.2.3 on 2023-10-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('START', 'Start'), ('UPDATE', 'Update'), ('MS', 'Milestone'), ('END', 'End')], default='Start', max_length=10),
        ),
    ]
