# Generated by Django 4.2.3 on 2023-12-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='journeyID',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('Start', 'Start'), ('Update', 'Update'), ('Milestone', 'Milestone'), ('End', 'End')], default='Update', max_length=10),
        ),
    ]
