# Generated by Django 4.2.3 on 2023-12-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_remove_post_journeyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='journeyID',
            field=models.TextField(blank=True),
        ),
    ]
