# Generated by Django 4.2.3 on 2023-12-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_journeyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='journeyID',
            field=models.UUIDField(),
        ),
    ]
