# Generated by Django 4.2.3 on 2023-12-14 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_post_journeyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='journeyID',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
