# Generated by Django 4.2.3 on 2023-12-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_rename_journeyid_post_journeyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='video',
        ),
    ]
