# Generated by Django 4.2.3 on 2024-01-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_remove_postattachment_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='image',
        ),
        migrations.AddField(
            model_name='postattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments'),
        ),
    ]
