# Generated by Django 4.2.3 on 2024-01-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_people_you_may_know'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendshiprequest',
            name='journeyid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
