# Generated by Django 4.2.3 on 2024-02-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_friendshiprequest_journeyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='journey_count',
            field=models.IntegerField(default=0),
        ),
    ]
