# Generated by Django 4.2.3 on 2024-02-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_journey_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='journey_count',
            new_name='journeys_count',
        ),
    ]
