# Generated by Django 4.2.3 on 2024-03-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_journey_count_user_journeys_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, default='', max_length=40),
        ),
    ]
