# Generated by Django 4.2.3 on 2024-03-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
