# Generated by Django 4.2.3 on 2024-03-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, default='', max_length=40),
        ),
    ]
