# Generated by Django 4.2.3 on 2024-03-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, default='', max_length=40, unique=True),
        ),
    ]
