# Generated by Django 4.2.3 on 2024-02-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0008_journey_only_me'),
        ('notification', '0003_alter_notification_type_of_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journey.journey'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('new_friendrequest', 'New friendrequest'), ('accepted_friendrequest', 'Accepted friendrequest'), ('rejected_friendrequest', 'Rejected friendrequest'), ('post_like', 'Post like'), ('post_comment', 'Post comment'), ('companion_request', 'Companion request'), ('accepted_companionrequest', 'Accepted companionrequest'), ('rejected_companionrequest', 'Rejected companionrequest'), ('journey_follow', 'Followed journey')], max_length=50),
        ),
    ]
